### ISSUE TITLE
安装完，重启后，显示器显示Ubuntu启动信息后，再也进不了桌面。

### ISSUE THREAD

**Issue by HonestQiao** [soulteary/ubuntu-remote-control-helper#2]
1. 安装完，重启后，显示器显示Ubuntu启动信息后，再也进不了桌面。
2. 远程桌面，也无法连接
3. secret-tool lookup xdg:schema org.gnome.RemoteDesktop.RdpCredentials 返回为空
4. urch执行提示上述指令执行失败
5.  printf "{'username': <'username'>, 'password': <'password'>}" | secret-tool store -l 'GNOME Remote Desktop RDP credentials' xdg:schema org.gnome.RemoteDesktop.RdpCredentials 执行hang住不动

要恢复的话，按什么途径操作？

**Comment by soulteary** [comment]
需要按照博客步骤进行，这个操作现象大概率是没有处理完毕 keychain。

**Comment by HonestQiao** [comment]
> 需要按照博客步骤进行，这个操作现象大概率是没有处理完毕 keychain。

升级到23.04，然后按照手工处理方式重新弄了一遍，现在能进了。

**Comment by soulteary** [comment]
结合另外一条 issue，有一个可能，是在解锁 keyring 的时候，因为系统子版本携带的 keyring 管理软件的 strore 不同，导致 RdpCredentials 获取不到，以及因为不同的 store 没有被解锁，程序执行的时候，会等待用户输入密码（hang住现象）。

解决方案，可能需要志愿者提供 store name 或者帮忙翻找下 keyring 的代码里使用的 store name，我做修正。

至于不能进系统，如果有开启 ssh， 连上去之后，service supervisor stop ，应该就可以了。（关闭掉守护的，可能会因为没解锁 keyring 导致 hang 住的程序。
