### ISSUE TITLE
安装完成后重启，卡在了/dev/neme0n1p2:recovering jour这个界面

### ISSUE THREAD

**Issue by simplelp** [soulteary/ubuntu-remote-control-helper#3]
你好，我在ubantu22.04系统上安装了两次；两次都出现开机假死，一直进不了系统；

第二次安装过程我看到有一条报错信息，大概意思是没有相关文件，但是文件名忘记了是什么了；
我是通过你的博客Urch 安装脚本自动安装的。

安装完成重启，当主板自检完成后，进入黑屏，屏幕显示：
/dev/neme0n1p2: recovering jour........
/dev/neme0n1p2: clearing orphaned inode.........
第一次和第二次出现的情况都是一样的，黑屏假死状态，一直进不了桌面。

开机启动按住shift键可以进行引导恢复界面
请问后续怎么操作可以解决这个问题？不想再重新装系统了。

**Comment by soulteary** [comment]
可以参考一下 https://github.com/soulteary/ubuntu-remote-control-helper/issues/2 这条里我补充的回复，这两条结合在一起，大概原因可以推测是因为 keyring store name 不同。


在不更新程序的前提下，如果是新系统，直接把 keyring 里的 store 都删除掉，然后启用 rdp 服务，等 keyring 中有新的 store 之后，解锁后，按照文章走一遍就好了。

@simplelp
